version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GIT_REPO: https://github.com/ximass/atividade_GCS.git
        GIT_BRANCH: staging
    container_name: laravel-staging-app
    env_file:
      - ../.env.staging
    volumes:
      - ../:/var/www/html:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    container_name: laravel-staging-nginx
    volumes:
      - ../:/var/www/html:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
