version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    volumes:
      - ./app:/var/www:ro
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
