version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: laravel-prod-app
    env_file:
      - ../.env.production
    volumes:
      - ../:/var/www/html:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    container_name: laravel-prod-nginx
    volumes:
      - ../:/var/www/html:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
