version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: laravel-prod-app
    env_file:
      - ../.env.production
    volumes:
      - ../:/var/www:ro
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-prod-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www:ro
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
