version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.production
    container_name: laravel-prod-app
    env_file:
      - ../.env.production
    volumes:
      # Volume separado para storage (uploads, logs, etc.)
      - laravel_prod_storage:/var/www/storage
      # Volume para cache do bootstrap
      - laravel_prod_bootstrap_cache:/var/www/bootstrap/cache
    networks:
      - laravel_prod_net

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-prod-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes_from:
      - app:ro
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_prod_net

volumes:
  laravel_prod_storage:
  laravel_prod_bootstrap_cache:

networks:
  laravel_prod_net:
    driver: bridge
