version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: laravel-staging-app
    env_file:
      - ../.env.staging
    volumes:
      - ../project-staging:/var/www
    networks:
      - laravel_net

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-staging-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
